version: '3.9'

services:
  laravel-todopostgres:
    container_name: laravel-todopostgres
    image: saugat23/laravel-todopostgres:1.0.2
    build: .
    ports: 
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}

